version: "3.8"
services:
    server-1:
        build: .
        env_file: .env
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=US/Pacific
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ./data/code-server-1/config:/home/coder
            - ./data/code-server-1/config/workspace:/home/coder/project
        ports:
            - 8098:8443
            - 8333:5000
        restart: unless-stopped
    server-2:
        build: .
        env_file: .env
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=US/Pacific
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ./data/code-server-2/config:/home/coder
            - ./data/code-server-2/config/workspace:/home/coder/project
        ports:
            - 8099:8443
            - 8334:5000
        restart: unless-stopped
