version: "3.8"
services:
    code-server-1:
        build: .
        env_file: .env
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=US/Pacific
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ./data/code-server-1/config:/config
        ports:
            - 8098:8443
        restart: unless-stopped
    code-server-2:
        build: .
        env_file: .env
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=US/Pacific
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ./data/code-server-2/config:/config
        ports:
            - 8099:8443
        restart: unless-stopped
